<%@ Page Title="" Language="C#" MasterPageFile="~/Master/almostHome.Master" AutoEventWireup="true" CodeBehind="RptAnimals.aspx.cs" Inherits="AlmostHome.Pages.Admin.Report.RptAnimals" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <div class="container main-content">
        <div class="card-body">
            <a class="btn btn-default btn-round btn-sm float-right" href="/Pages/Admin/Reports.aspx">
                <i class="material-icons">keyboard_backspace</i> Return to Report Home
                <div class="ripple-container"></div>
            </a>
            <asp:Panel ID="reportPanel" runat="server">
                <div class="text-center font-weight-bold" style="font-size: x-large"><asp:Label ID="lblReporTitle" runat="server" Text=""/></div>
                <div class="text-center">(From: <asp:Label ID="lblFrom" runat="server" Text=""/>  To: <asp:Label ID="lblTo" runat="server" Text="" />)</div>
                <br/>
                <div class="table-responsive">
                    <table class="table" style="font-size: 14px;">
                        <thead class=" text-primary">
                            <tr>
                                <th>Animal Name</th>
                                <th>AnimalType</th>
                                <th>AnimalAge</th>
                                <th>Children</th>
                                <th>Secure Garden</th>
                                <th>OtherPets</th>
                                <th>Rehomed</th>
                                <th>Rehomed Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            <asp:ListView ID="lstGrid" runat="server">
                                <ItemTemplate>
                                    <tr>
                                        <td><%#Eval("AnimalName")%></td>
                                        <td><%#Eval("AnimalType")%></td>
                                        <td><%#Eval("AnimalAge")%></td>
                                        <td><%#Eval("Children")%></td>
                                        <td><%#Eval("SecureGarden")%></td>
                                        <td><%#Eval("OtherPets")%></td>
                                        <td><%#Eval("Rehomed")%></td>
                                        <td><%#Eval("RehomedDate", "{0:d}")%></td>
                                    </tr>
                                </ItemTemplate>
                            </asp:ListView>
                        </tbody>
                    </table>
                </div>
                <br/>
                <hr/>
                <div class="float-right small font-weight-bold">Total Records: <asp:Label ID="lblTotalRecords" runat="server" Text=""/></div>
                <div class="float-left small font-weight-bold">Report Date: <asp:Label ID="lblReportDate" runat="server" Text="" /></div><br/>
                <div class="float-left small font-weight-bold">Generated By: <asp:Label ID="lblGeneratedBy" runat="server" Text=""/></div>
            </asp:Panel>
            <asp:Button ID="btnDownload" runat="server" Text="Export To PDF" OnClick="btnDownload_OnClick" CssClass="btn btn-info btn-sm float-right" />
        </div>
    </div>
</asp:Content>
