<%@ Page Title="" Language="C#" MasterPageFile="~/Master/almostHome.Master" AutoEventWireup="true" CodeBehind="RptVolunteerApplications.aspx.cs" Inherits="AlmostHome.Pages.Admin.Report.RptVolunteerApplications" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <div class="container main-content">
        <div class="card-body">
            <a class="btn btn-default btn-round btn-sm float-right" href="/Pages/Admin/Reports.aspx">
                <i class="material-icons">keyboard_backspace</i> Return to Report Home
                <div class="ripple-container"></div>
            </a>
            <asp:Panel ID="reportPanel" runat="server">
                <div class="text-center font-weight-bold" style="font-size: x-large"><asp:Label ID="lblReporTitle" runat="server" Text=""/></div>
                <div class="text-center">(From: <asp:Label ID="lblFrom" runat="server" Text=""/>  To: <asp:Label ID="lblTo" runat="server" Text="" />)</div>
                <br/>
                <div class="table-responsive">
                    <table class="table" style="font-size: 14px;">
                        <thead class=" text-primary">
                            <tr>
                                <th>Applied Date</th>
                                <th>Volunteer Name</th>
                                <th>Contact Number</th>
                                <th>Email</th>
                                <th>Availability</th>
                                <th>PreferredUnit</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            <asp:ListView ID="lstGrid" runat="server">
                                <ItemTemplate>
                                    <tr>
                                        <td><%#Eval("ApplicationDate", "{0:d}")%></td>
                                        <td><%#Eval("VolunteerName")%></td>
                                        <td><%#Eval("ContactNumber")%></td>
                                        <td><%#Eval("EmailAddress")%></td>
                                        <td><%#Eval("Availability")%></td>
                                        <td><%#Eval("PreferredUnit")%></td>
                                        <td><%#Eval("Status")%></td>
                                    </tr>
                                </ItemTemplate>
                            </asp:ListView>
                        </tbody>
                    </table>
                </div>
                <br/>
                <hr/>
                <div class="float-right small font-weight-bold">Total Records: <asp:Label ID="lblTotalRecords" runat="server" Text=""/></div>
                <div class="float-left small font-weight-bold">Report Date: <asp:Label ID="lblReportDate" runat="server" Text="" /></div><br/>
                <div class="float-left small font-weight-bold">Generated By: <asp:Label ID="lblGeneratedBy" runat="server" Text=""/></div>
            </asp:Panel>
            <asp:Button ID="btnDownload" runat="server" Text="Export To PDF" OnClick="btnDownload_OnClick" CssClass="btn btn-info btn-sm float-right" />
        </div>
    </div>
</asp:Content>
